### ISSUE TITLE
Add database connection

### ISSUE THREAD

**Issue by timhabermaas** [timhabermaas/flashdance-backend#2]
## Todo
- [ ] Add migration infrastructure
- [ ] Add seeds (for seats)
- [ ] Connect from Sinatra using Sequel
